### ISSUE TITLE
main_lorawan.c file missing

### ISSUE THREAD

**Issue by induthings-coder** [Lora-net/lora_edge_tracker_ref_design#3]
I'm taking the first touch with the project and I found this:

..\Src\apps\LoRaWAN\main_lorawan.c

LoRaWAN folder and file doesn't exist...

Best regards

**Comment by smtcbboulet** [comment]
Hello,

thanks for report this, I've fixed the makefile, you can pull the project.

let me know,

regards,

Benjamin

**Comment by induthings-coder** [comment]
KEIL project still having the main_lorawan.c file included. I suppose I can delete it...

**Comment by smtcbboulet** [comment]
I gonna update the keil project, the path and name are not the good one for the lorawan example
